name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  # Architecture
  freezed: ^0.15.0+1
  freezed_annotation: ^0.15.0

dev_dependencies:
  mocktail: ^0.2.0
  build_runner: ^2.1.4
  json_serializable: ^5.0.2
  lints: ^1.0.0
  test: ^1.16.0
